# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Elisa Muscarella
# Description of the Site
description: PhD Candidate in Economics | Political Economy & Public Economics
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: economics, political economy, public economics, gender, PhD, Barcelona
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: #https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: elisa.muscarella@ub.edu
facebook_username: 
twitter_username: ElisaMuscarella
instagram_username:  
linkedin_username: elisa-muscarella
github_username:  elisamuscarella
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
bluesky_username: elisamuscarella.bsky.social

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname:  

# Name of the Author
author-name: Elisa Muscarella
# URL for the Image of the Author
author-image: /assets/images/DSCF4339.JPG
# 60 Words About the Author
author-about: I am a PhD candidate in Economics at the University of Barcelona and an affiliated researcher at the Institut d'Economia de Barcelona (IEB) and the Institutions, Politics and Economics Research Centre. My research interests include political economy and public economics with a gender perspective.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.ub.edu/school-economics/phd-student/elisa-muscarella/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
